export const LANGUAGE_CODES = [
    // { language: "Zulu", code: "zu" },
    // { language: "Amharic", code: "am" },
    // { language: "Arabic", code: "ar" },
    // { language: "Basque", code: "eu" },
    { language: "Bengali", code: "bn" },
    { language: "Punjabi", code: "pa" },
    { language: "Oriya", code: "or" },
    { language: "English (US)", code: "en" },
    { language: "Gujarati", code: "gu" },
    { language: "Sanskrit", code: "sa" },
    { language: "Hindi", code: "hi" },
    { language: "Awadhi", code: "awa" },
    { language: "Bhojpuri", code: "bho" },
    { language: "Maithili", code: "mai" },
    { language: "Nepali", code: "ne" },
    { language: "Dogri", code: "doi" },
    { language: "Kannada", code: "kn" },
    { language: "Konkani", code: "gom" },
    { language: "Malayalam", code: "ml" },
    { language: "Marathi", code: "mr" },
    { language: "Tamil", code: "ta" },
    { language: "Sinhala", code: "si" },
    { language: "Telugu", code: "te" }//,
];